### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by kilakewe** [KyleTryon/OpenCanv#1]
Hi there, 

I was interested in what you've created and was wondering if you could specify a license for this repo. I know you've mentioned that the code is open-source but I just wanted to clarify how open that is. 

Thanks!

**Comment by KyleTryon** [comment]
Hey @kilakewe There isn't actually much code in this repo. I made the color picker and didn't get much farther. I welcome you to use anything you wish here but I will most likely archive the project. I may take another shot at it with React in the future rather than start up this repo again.

If you need a license, feel free to PR one and ill approve it 👍 otherwise you have my "verbal" approval to use as you wish
